---
apiVersion: apps/v1 
kind: Deployment
metadata:
  annotations:
    fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project={{ .Values.serviceName }}&var-version={{ .Values.imageTag }}
  labels:
    app: {{ .Values.serviceName }}
    version: "{{ .Values.imageTag }}"
  name: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.numOfPods | default 2 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      annotations:
        fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project={{ .Values.serviceName }}&var-version={{ .Values.imageTag }}
      labels:
        app: {{ .Values.serviceName }}
        version: "{{ .Values.imageTag }}"
        date: "{{ date "20060102-150405" .Release.Time }}"
    spec:
      serviceAccountName: jgroups-kubeping-service-account
      {{- if (.Values.acrSecretName) }} 
      imagePullSecrets:
        - name: {{ .Values.acrSecretName }}
      {{- end }}
      containers:
      - env:
        {{- if (.Values.dnsEntry) }} 
        - name: DNS_ENTRY
          value: {{ .Values.dnsEntry }}
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_DNS_ENTRY
          value: {{ .Values.dnsEntry }}
        {{- end }}
        {{- if (.Values.externalDnsEntry) }} 
        - name: EXTERNAL_DNS_ENTRY
          value: {{ .Values.externalDnsEntry }}
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_EXTERNAL_DNS_ENTRY
          value: {{ .Values.externalDnsEntry }}
        {{- end }}
        - name: KUBERNETES_SERVICE_NAME
          value: {{ .Values.serviceName }}
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_KUBERNETES_SERVICE_NAME
          value: {{ .Values.serviceName }}
        - name: KUBERNETES_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_KUBERNETES_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: HELM_RELEASE_TIME
          value: "{{ date "20060102-150405" .Release.Time }}"
        - name: MY_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: JVM_MAX_HEAP_SIZE
          value: "{{ .Values.jvmMaxHeapSizeMB }}m"
        # Set the minimum memory that will be available on the node to assign to the container to be the jvmMaxHeapSizeMB plus 128 MB 
        # for the native heap and operation system processes associated with running Java
        # See https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/#motivation-for-memory-requests-and-limits
        # and https://www.alibabacloud.com/blog/kubernetes-demystified-restrictions-on-java-application-resources_594108
        resources:
          requests:
            memory: "{{ add 128 .Values.jvmMaxHeapSizeMB }}Mi"
        image: {{ .Values.dockerRepo }}interface-hl7jgroups-soapclient:{{ .Values.imageTag }}            
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 15
          periodSeconds: 5
        name: hl7-messaging-jgroups
        ports:
        - containerPort: 3200
          name: http
          protocol: TCP
        - containerPort: 7800
          name: jgroups
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 15
          periodSeconds: 5
        securityContext:
          privileged: false     
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 30 }}